// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {backend} from '../models';
import {context} from '../models';

export function ChatWithAI(arg1:string,arg2:Array<string>):Promise<string>;

export function CreateCategory(arg1:string,arg2:any,arg3:any):Promise<backend.Category>;

export function CreateColorPreset(arg1:string,arg2:string,arg3:boolean):Promise<backend.ColorPreset>;

export function CreateNote(arg1:string,arg2:string,arg3:string,arg4:string,arg5:number):Promise<backend.Note>;

export function CreateNoteMD(arg1:string,arg2:string,arg3:string,arg4:number):Promise<backend.Note>;

export function CreateNoteMDWithType(arg1:string,arg2:string,arg3:string,arg4:number,arg5:number):Promise<backend.Note>;

export function DeleteCategory(arg1:number):Promise<void>;

export function DeleteColorPreset(arg1:number):Promise<void>;

export function DeleteNote(arg1:number):Promise<void>;

export function ExecuteScript(arg1:number):Promise<backend.ScriptResult>;

export function GetAIConfig():Promise<backend.AIConfig>;

export function GetCategoryContent(arg1:number):Promise<string>;

export function GetConfigFilePath():Promise<string>;

export function GetContext():Promise<context.Context>;

export function GetImageContent(arg1:string):Promise<string>;

export function GetLogFilePath():Promise<string>;

export function GetNoteContent(arg1:number):Promise<string>;

export function GetPDFContent(arg1:number):Promise<string>;

export function GetPDFPath(arg1:number):Promise<string>;

export function ImportPDF(arg1:string,arg2:string,arg3:number):Promise<backend.Note>;

export function ListCategories():Promise<Array<backend.Category>>;

export function ListColorPresets():Promise<Array<backend.ColorPreset>>;

export function ListNotes(arg1:any):Promise<Array<backend.Note>>;

export function LogFrontend(arg1:string):Promise<void>;

export function ReadLogFile():Promise<string>;

export function RequireBiometric(arg1:string):Promise<void>;

export function SaveImage(arg1:string):Promise<string>;

export function SetTheme(arg1:boolean):Promise<void>;

export function UpdateAIConfig(arg1:backend.AIConfig):Promise<void>;

export function UpdateCategory(arg1:number,arg2:string,arg3:any,arg4:any):Promise<void>;

export function UpdateColorPreset(arg1:number,arg2:string,arg3:string,arg4:boolean):Promise<void>;

export function UpdateNote(arg1:number,arg2:string,arg3:string,arg4:string,arg5:string,arg6:number):Promise<void>;

export function UpdateNoteMD(arg1:number,arg2:string,arg3:string,arg4:string,arg5:number):Promise<void>;

export function UpdatePDFPage(arg1:number,arg2:number):Promise<void>;
