// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChatWithAI(arg1, arg2) {
  return window['go']['backend']['App']['ChatWithAI'](arg1, arg2);
}

export function CreateCategory(arg1, arg2, arg3) {
  return window['go']['backend']['App']['CreateCategory'](arg1, arg2, arg3);
}

export function CreateColorPreset(arg1, arg2, arg3) {
  return window['go']['backend']['App']['CreateColorPreset'](arg1, arg2, arg3);
}

export function CreateNote(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['backend']['App']['CreateNote'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateNoteMD(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['CreateNoteMD'](arg1, arg2, arg3, arg4);
}

export function CreateNoteMDWithType(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['backend']['App']['CreateNoteMDWithType'](arg1, arg2, arg3, arg4, arg5);
}

export function DeleteCategory(arg1) {
  return window['go']['backend']['App']['DeleteCategory'](arg1);
}

export function DeleteColorPreset(arg1) {
  return window['go']['backend']['App']['DeleteColorPreset'](arg1);
}

export function DeleteNote(arg1) {
  return window['go']['backend']['App']['DeleteNote'](arg1);
}

export function ExecuteScript(arg1) {
  return window['go']['backend']['App']['ExecuteScript'](arg1);
}

export function GetAIConfig() {
  return window['go']['backend']['App']['GetAIConfig']();
}

export function GetCategoryContent(arg1) {
  return window['go']['backend']['App']['GetCategoryContent'](arg1);
}

export function GetConfigFilePath() {
  return window['go']['backend']['App']['GetConfigFilePath']();
}

export function GetContext() {
  return window['go']['backend']['App']['GetContext']();
}

export function GetImageContent(arg1) {
  return window['go']['backend']['App']['GetImageContent'](arg1);
}

export function GetLogFilePath() {
  return window['go']['backend']['App']['GetLogFilePath']();
}

export function GetNoteContent(arg1) {
  return window['go']['backend']['App']['GetNoteContent'](arg1);
}

export function GetPDFContent(arg1) {
  return window['go']['backend']['App']['GetPDFContent'](arg1);
}

export function GetPDFPath(arg1) {
  return window['go']['backend']['App']['GetPDFPath'](arg1);
}

export function ImportPDF(arg1, arg2, arg3) {
  return window['go']['backend']['App']['ImportPDF'](arg1, arg2, arg3);
}

export function ListCategories() {
  return window['go']['backend']['App']['ListCategories']();
}

export function ListColorPresets() {
  return window['go']['backend']['App']['ListColorPresets']();
}

export function ListNotes(arg1) {
  return window['go']['backend']['App']['ListNotes'](arg1);
}

export function LogFrontend(arg1) {
  return window['go']['backend']['App']['LogFrontend'](arg1);
}

export function MigrateBase64ImagesToLocal() {
  return window['go']['backend']['App']['MigrateBase64ImagesToLocal']();
}

export function ReadLogFile() {
  return window['go']['backend']['App']['ReadLogFile']();
}

export function RequireBiometric(arg1) {
  return window['go']['backend']['App']['RequireBiometric'](arg1);
}

export function SaveImage(arg1) {
  return window['go']['backend']['App']['SaveImage'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['backend']['App']['SetTheme'](arg1);
}

export function UpdateAIConfig(arg1) {
  return window['go']['backend']['App']['UpdateAIConfig'](arg1);
}

export function UpdateCategory(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['UpdateCategory'](arg1, arg2, arg3, arg4);
}

export function UpdateColorPreset(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['UpdateColorPreset'](arg1, arg2, arg3, arg4);
}

export function UpdateNote(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['backend']['App']['UpdateNote'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UpdateNoteMD(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['backend']['App']['UpdateNoteMD'](arg1, arg2, arg3, arg4, arg5);
}

export function UpdatePDFPage(arg1, arg2) {
  return window['go']['backend']['App']['UpdatePDFPage'](arg1, arg2);
}
