// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateCategory(arg1, arg2, arg3) {
  return window['go']['backend']['App']['CreateCategory'](arg1, arg2, arg3);
}

export function CreateColorPreset(arg1, arg2) {
  return window['go']['backend']['App']['CreateColorPreset'](arg1, arg2);
}

export function CreateNote(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['backend']['App']['CreateNote'](arg1, arg2, arg3, arg4, arg5);
}

export function CreateNoteMD(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['CreateNoteMD'](arg1, arg2, arg3, arg4);
}

export function DeleteCategory(arg1) {
  return window['go']['backend']['App']['DeleteCategory'](arg1);
}

export function DeleteColorPreset(arg1) {
  return window['go']['backend']['App']['DeleteColorPreset'](arg1);
}

export function DeleteNote(arg1) {
  return window['go']['backend']['App']['DeleteNote'](arg1);
}

export function GetContext() {
  return window['go']['backend']['App']['GetContext']();
}

export function ListCategories() {
  return window['go']['backend']['App']['ListCategories']();
}

export function ListColorPresets() {
  return window['go']['backend']['App']['ListColorPresets']();
}

export function ListNotes(arg1) {
  return window['go']['backend']['App']['ListNotes'](arg1);
}

export function LogFrontend(arg1) {
  return window['go']['backend']['App']['LogFrontend'](arg1);
}

export function SetTheme(arg1) {
  return window['go']['backend']['App']['SetTheme'](arg1);
}

export function UpdateCategory(arg1, arg2, arg3, arg4) {
  return window['go']['backend']['App']['UpdateCategory'](arg1, arg2, arg3, arg4);
}

export function UpdateColorPreset(arg1, arg2, arg3) {
  return window['go']['backend']['App']['UpdateColorPreset'](arg1, arg2, arg3);
}

export function UpdateNote(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['backend']['App']['UpdateNote'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function UpdateNoteMD(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['backend']['App']['UpdateNoteMD'](arg1, arg2, arg3, arg4, arg5);
}
